// Users
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

// Page
export const ADD_PAGE_REQUEST = "ADD_PAGE_REQUEST";
export const ADD_PAGE_SUCCESS = "ADD_PAGE_SUCCESS";
export const ADD_PAGE_FAILED = "ADD_PAGE_FAILED";

// Greeting
export const GET_GREETING_REQUEST = "GET_GREETING_REQUEST";
export const GET_GREETING_SUCCESS = "GET_GREETING_SUCCESS";
export const GET_GREETING_FAILED = "GET_GREETING_FAILED";

export const ADD_GREETING_REQUEST = "ADD_GREETING_REQUEST";
export const ADD_GREETING_SUCCESS = "ADD_GREETING_SUCCESS";
export const ADD_GREETING_FAILED = "ADD_GREETING_FAILED";

// Persistent Menu
export const GET_MENU_REQUEST = "GET_MENU_REQUEST";
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const GET_MENU_FAILED = "GET_MENU_FAILED";

export const ADD_MENU_REQUEST = "ADD_MENU_REQUEST";
export const ADD_MENU_SUCCESS = "ADD_MENU_SUCCESS";
export const ADD_MENU_FAILED = "ADD_MENU_FAILED";

// Ice Breaker
export const GET_ICE_BREAKER_REQUEST = "GET_ICE_BREAKER_REQUEST";
export const GET_ICE_BREAKER_SUCCESS = "GET_ICE_BREAKER_SUCCESS";
export const GET_ICE_BREAKER_FAILED = "GET_ICE_BREAKER_FAILED";

export const ADD_ICE_BREAKER_REQUEST = "ADD_ICE_BREAKER_REQUEST";
export const ADD_ICE_BREAKER_SUCCESS = "ADD_ICE_BREAKER_SUCCESS";
export const ADD_ICE_BREAKER_FAILED = "ADD_ICE_BREAKER_FAILED";

// Contact
export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILED = "CONTACT_US_FAILED";

// Story reply
export const ADD_STORY_REPLY_REQUEST = "ADD_STORY_REPLY_REQUEST";
export const ADD_STORY_REPLY_SUCCESS = "ADD_STORY_REPLY_SUCCESS";
export const ADD_STORY_REPLY_FAILED = "ADD_STORY_REPLY_FAILED";

export const GET_STORY_REPLY_REQUEST = "GET_STORY_REPLY_REQUEST";
export const GET_STORY_REPLY_SUCCESS = "GET_STORY_REPLY_SUCCESS";
export const GET_STORY_REPLY_FAILED = "GET_STORY_REPLY_FAILED";

// Story mention
export const ADD_STORY_MENTION_REQUEST = "ADD_STORY_MENTION_REQUEST";
export const ADD_STORY_MENTION_SUCCESS = "ADD_STORY_MENTION_SUCCESS";
export const ADD_STORY_MENTION_FAILED = "ADD_STORY_MENTION_FAILED";

export const GET_STORY_MENTION_REQUEST = "GET_STORY_MENTION_REQUEST";
export const GET_STORY_MENTION_SUCCESS = "GET_STORY_MENTION_SUCCESS";
export const GET_STORY_MENTION_FAILED = "GET_STORY_MENTION_FAILED";
