// Users
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

// Page
export const ADD_PAGE_REQUEST = "ADD_PAGE_REQUEST";
export const ADD_PAGE_SUCCESS = "ADD_PAGE_SUCCESS";
export const ADD_PAGE_FAILED = "ADD_PAGE_FAILED";

// Greeting
export const GET_GREETING_REQUEST = "GET_GREETING_REQUEST";
export const GET_GREETING_SUCCESS = "GET_GREETING_SUCCESS";
export const GET_GREETING_FAILED = "GET_GREETING_FAILED";

export const ADD_GREETING_REQUEST = "ADD_GREETING_REQUEST";
export const ADD_GREETING_SUCCESS = "ADD_GREETING_SUCCESS";
export const ADD_GREETING_FAILED = "ADD_GREETING_FAILED";
