export const features = [
  {
    title: "Greetings",
    desc: "Automated never means generic here at BOLDbot. These are the first responses to a buyer’s DM. Each store can customize their greetings to cater to the needs and wants of their clientele as well as target markets. Design your own custom greetings which define you as a store when interacting with patrons.",
    backgroundImage: "linear-gradient(19deg, #21D4FD 0%, #B721FF 100%)",
    backgroundColor: "#21D4FD",
    imgSrc: "/assets/greeting.png",
    pageHref: "/dashboard/greetings",
  },
  {
    title: "Ice Breakers",
    desc: "Increase efficiency of service by introducing Ice Breakers to your customer’s DMs. These standardised texts cover certain frequently asked question for your patrons to choose from. This allows the customer to verbalise and convey their concerns or queries to the store with ease.",
    backgroundImage: "linear-gradient(135deg, #8BC6EC 0%, #9599E2 100%)",
    backgroundColor: "#8BC6EC",
    imgSrc: "/assets/iceBreaker.png",
    pageHref: "/dashboard/ice-breakers",
  },
  {
    title: "Persistent Menu",
    desc: "Made an error along the way? No worries we got you! The persistent menu in the tab allows for customers to navigate the conversation better by giving them the option of not just starting over but also the choice to introduce other points of interest.",
    backgroundImage: "linear-gradient(45deg, #85FFBD 0%, #FFFB7D 100%)",
    backgroundColor: "#85FFBD",
    imgSrc: "/assets/persistentMenu.png",
    pageHref: "/dashboard/persistent-menu",
  },
  {
    title: "Custom Replies",
    desc: "Time is money here at BOLDbot, make your interactions with patrons faster with our custom reply feature. Employing this feature allows the user to design textual responses unique to trigger words. Custom replies cut out the need for multiple drop menus and make customer servicing rapid.",
    backgroundImage: "linear-gradient(45deg, #FBDA61 0%, #FF5ACD 100%)",
    backgroundColor: "#FBDA61",
    imgSrc: "/assets/customReplies.png",
    pageHref: "/dashboard/greetings",
  },
  {
    title: "Story Replies",
    desc: "Set customised automated replies whenever someone replies to your story with the keyword of your choice! This will help you take product advertisements and brand/event promotions to a new level! Set a custom word for your followers to reply to your story, set a custom response to that word with respective information of that event and relax while BOLDbot does the job for you!",
    backgroundImage: "linear-gradient(to top, #a18cd1 0%, #fbc2eb 100%)",
    backgroundColor: "#FBDA61",
    imgSrc: "/assets/storyReplies.png",
    pageHref: "/dashboard/story",
  },
  {
    title: "Story Mentions",
    desc: "Set customisable automated replies whenever someone mentions you in their Instagram stories! Assign unique texts to keep your interactions going with patrons and followers.",
    backgroundImage: "linear-gradient(90deg, #d7d2cc 0%, #304352 100%);",
    backgroundColor: "#304352",
    imgSrc: "/assets/storyMentions.png",
    pageHref: "/dashboard/story",
  },
];
