export const features = [
  {
    title: "Greetings",
    desc: "Automated never means generic here at BOLD. These are the first responses to a buyer’s DM. Each store can customize their greetings to cater to the needs and wants of their clientele as well as target markets. Design your own custom greetings which define you as a store when interacting with patrons.",
    backgroundImage: "linear-gradient(19deg, #21D4FD 0%, #B721FF 100%)",
    backgroundColor: "#21D4FD",
    id: "Greetings",
    imgSrc: "/assets/greeting.png",
    pageHref: "/dashboard/greetings",
  },
  {
    title: "Ice Breakers",
    desc: "Increase efficiency of service by introducing Ice Breakers to your customer’s DMs. These standardised texts cover certain frequently asked question for your patrons to choose from. This allows the customer to verbalise and convey their concerns or queries to the store with ease.",
    backgroundImage: "linear-gradient(135deg, #8BC6EC 0%, #9599E2 100%)",
    backgroundColor: "#8BC6EC",
    id: "IceBreakers",
    imgSrc: "/assets/iceBreaker.png",
    pageHref: "/dashboard/ice-breakers",
  },
  {
    title: "Persistent Menu",
    desc: "Made an error along the way? No worries we got you! The persistent menu in the tab allows for customers to navigate the conversation better by giving them the option of not just starting over but also the choice to introduce other points of interest.",
    backgroundImage: "linear-gradient(45deg, #85FFBD 0%, #FFFB7D 100%)",
    backgroundColor: "#85FFBD",
    id: "PersistentMenu",
    imgSrc: "/assets/persistentMenu.png",
    pageHref: "/dashboard/persistent-menu",
  },
  {
    title: "Custom Replies",
    desc: "Don’t know how or what to say? Let BOLDbot help! The quick reply feature presents customers with a set of buttons in-conversation to respond with. An array of options to simplify customer experience with your store.",
    backgroundImage: "linear-gradient(45deg, #FBDA61 0%, #FF5ACD 100%)",
    backgroundColor: "#FBDA61",
    id: "CustomReplies",
    imgSrc: "/assets/quickReplies.png",
    pageHref: "/dashboard/greetings",
    comingSoon: true,
  },
];
